### ISSUE TITLE
Unable to serve file under other hostnames

### ISSUE THREAD

**Issue by lra** [jubos/fake-s3#114]
Fakes3 is unable to serve files under another hostname.
I'm using fakes3 0.2.1.

Here's how to reproduce the problem:

Save the file `s3client.py`:
```python
from boto.s3.connection import S3Connection, OrdinaryCallingFormat

s3 = S3Connection('', '', is_secure=False, port=4567, host='localhost', calling_format=OrdinaryCallingFormat())
bucket = s3.create_bucket('created_bucket')
key = bucket.new_key('created_file_in_the_bucket')
key.set_contents_from_string('This is the content of the created file\n')
for item in bucket.list():
    print item
    print item.get_contents_as_string()
```

Create the fakes3 root:
```bash
makdir fake_s3_root
```

Run fakes3 with the default localhost hostname:
```bash
fakes3 server --port=4567 --root=fake_s3_root
```

Launch `s3client.py` to create the `created_bucket` bucket and the `created_file_in_the_bucket` file.
```bash
$ python s3client.py 
<Key: created_bucket,created_file_in_the_bucket>
This is the content of the created file

```

Perfect, now curl the file:
```bash
$ curl http://localhost:4567/created_bucket/created_file_in_the_bucket
This is the content of the created file

```

Works great!

But now curl the same file with another hostname pointing to the same IP:

```bash
$ curl http://localhost.localdomain:4567/created_bucket/created_file_in_the_bucket
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist</Message><Key>created_bucket/created_file_in_the_bucket</Key><RequestId>1</RequestId><HostId>2</HostId></Error>
```

fakes3 does not serve the file, as it tries to look for it elsewhere:
```
No such file or directory @ rb_sysopen - /Users/analogue/tmp/fake_s3_root/localhost/created_bucket/created_file_in_the_bucket/.fakes3_metadataFFF/metadata
/usr/local/lib/ruby/gems/2.2.0/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:83:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:83:in `open'
/usr/local/lib/ruby/gems/2.2.0/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:83:in `get_object'
/usr/local/lib/ruby/gems/2.2.0/gems/fakes3-0.2.1/lib/fakes3/server.rb:94:in `do_GET'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/webrick/httpservlet/abstract.rb:106:in `service'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
localhost - - [10/Aug/2015:23:02:30 EDT] "GET /created_bucket/created_file_in_the_bucket HTTP/1.1" 404 220
- -> /created_bucket/created_file_in_the_bucket
```

For a reason I can't understand, fakes3 look for the file in:
```
Users/analogue/tmp/fake_s3_root/localhost/created_bucket/created_file_in_the_bucket/.fakes3_metadataFFF/metadata
```
Instead of looking at the file in the legit place:
```
Users/analogue/tmp/fake_s3_root/created_bucket/created_file_in_the_bucket/.fakes3_metadataFFF/metadata
```

Fakes3 tries to append the configure hostname `localhost` to the root folder.

Expected behavior:
When I launch fakes3 without a configured hostname, I expect fakes3 to serve any domain pointing to the IP it's running on the same way.

**Comment by ochrons** [comment]
I'm getting this same issue when trying to access Fake S3 from inside a Docker container with `fakes3` running on the host.

Using 172.17.0.1 as host address, resulting in a `No such file or directory - /home/xxx/s3root/172/testbucket/.fakes3_metadataFFF/metadata`

**Comment by landowskitomasz** [comment]
I have similar issue with fakes3 on docker. Any progress on that?

**Comment by bradgessler** [comment]
The offending code is at https://github.com/jubos/fake-s3/commit/bb35f3902a33b9c6d017faa255fa2986ba5e8bff#diff-aab88656cc39d9ecac1bb11128b9c777R217.

Its incorrectly assuming that the hostname is *not* an IP address. I think the check should look something like this:

```ruby
      if !@root_hostnames.include?(host) && host =~ /^(.+).s3.amazonaws.com$/
        s_req.bucket = $1
        s_req.is_path_style = false
      end
```

What I don't know is if that regexp check is correct. The other direction to go is to check if the host is an IP address (and skip this block).

**Comment by rehevkor5** [comment]
@jubos any chance you can give another person (or couple of people) push access & ownership to the gem on rubygems so that we can get some of these issues resolved?

**Comment by jubos** [comment]
Merged @bradgessler's change and cut a new point release.

**Comment by bradgessler** [comment]
Thanks @jubos!

**Comment by cthulu** [comment]
I'm still having this issue with 0.2.4 in Docker container:
`docker run --name local-fakes3 -v  /localpath/fakes3/:/fakes3_root lphoward/fake-s3 -r /fakes3_root -p 4569 -H localhost`
This explicitly sets host, but when I try to perform s3cmd (or anything else) from another linked container, trying to access a file `config` in a `my_bucket` I get:

```
Loading FakeS3 with /fakes3_root on port 4569 with hostname localhost
No such file or directory @ rb_sysopen - /fakes3_root/fakes3/my_bucket/.fakes3_metadataFFF/metadata
/var/lib/gems/2.1.0/gems/fakes3-0.2.4/lib/fakes3/file_store.rb:83:in `initialize'
```

The correct path should be `/fakes3_root/fakes3/my_bucket/config/.fakes3_metadataFFF/metadata`

**Comment by cthulu** [comment]
Actually I've figured out if I start the fakeS3 Docker container with `-r /fakes3_root -p 4569 -H fakes3`, this works! Makes sense after inspecting the ruby code, the linked container was using something 'unknown' to the fakes3 server.

**Comment by thekorn** [comment]
just as a side note for everyone who is using fakes3 in docker, and does not want to (or cannot) use the `-H <hostname>` "workaround": the solution is to link the fakes3 container using either `s3.amazonaws.com`or `s3.localhost` as hostname for the linked fakes3 container in your app, so something like:

```
fakes3:
  image: lphoward/fake-s3
  ports:
    - "4569:4569" 
web:
  build: .
  working_dir: /code
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - fakes3:s3.amazonaws.com
```

(refering to https://github.com/jubos/fake-s3/blob/master/lib/fakes3/server.rb#L53)

**Comment by hellosteadman** [comment]
Just to confirm, as of now there isn't a combination of settings that'll work in Docker, to get the copy operation to succeed. I'm guessing this wasn't the case in 2016, but sadly is now. Would love to see a resolution to this, so that I can upgrade to a newer version of fakes3; as it stands I'll need to go back to 0.2.5
