### ISSUE TITLE
Ruby 2.3.0: ERROR NoMethodError: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by ejennings-mdsol** [jubos/fake-s3#138]
When using Ruby 2.3.0, I see `ERROR NoMethodError: undefined method 'name' for nil:NilClass` errors.  Here is the backtrace:

```
ERROR NoMethodError: undefined method `name' for nil:NilClass
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/s3_object.rb:16:in `<=>'
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/xml_adapter.rb:118:in `=='
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/xml_adapter.rb:118:in `index'
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/xml_adapter.rb:118:in `append_objects_to_list_bucket_result'
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/xml_adapter.rb:159:in `block in bucket_query'
  .rvm/gems/ruby-2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
  .rvm/gems/ruby-2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
  .rvm/gems/ruby-2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/xml_adapter.rb:153:in `bucket_query'
  .rvm/gems/ruby-2.3.0/gems/fakes3-0.2.3/lib/fakes3/server.rb:84:in `do_GET'
  .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpservlet/abstract.rb:107:in `service'
  .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

Under ruby 2.2.2, I get:

```
 fakes3-0.2.3/lib/fakes3/xml_adapter.rb:118: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
 Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```

Under ruby 2.1.2 I get no warnings

Here is code to reproduce:

``` ruby
require 'aws-sdk'

fake_s3_dir = 'tmp'
fake_s3 = IO.popen("fakes3 -r #{fake_s3_dir} -p 4569")

bucket_name = 'my_test_bucket'
prefix = 'my_prefix'
key_name = "#{prefix}/foo.txt"

config = {
  access_key_id: 'key_id',
  secret_access_key: 'secret',
  aws_region: 'us-east-1',
  s3_endpoint: 'http://localhost:4569/'
}
client_options = {
  credentials: Aws::Credentials.new(config[:access_key_id], config[:secret_access_key]),
  region: config[:aws_region], endpoint: config[:s3_endpoint]
}
s3_client = Aws::S3::Client.new(client_options)
s3_resource = Aws::S3::Resource.new(client: s3_client)
bucket = s3_resource.bucket(bucket_name)

bucket.object(key_name).put(body: 'some_text')
bucket.objects(prefix: prefix).count

Process.kill('KILL', fake_s3.pid)
```

Code to fix this is in https://github.com/jubos/fake-s3/pull/137

**Comment by bjeanes** [comment]
I think this can be closed because #137 indicates the fix was committed to master.
