### ISSUE TITLE
NoMethodError: undefined method `Error' for #<FakeS3::FileStore:0x0055d10f10d9a8>

### ISSUE THREAD

**Issue by BLaurent** [jubos/fake-s3#142]
Hi,

I've been using fakes3 quite a lot those past month util I faced this ...
Do you know what can cause  this.

[2016-04-01 10:30:02] ERROR NoMethodError: undefined method `Error' for #<FakeS3::FileStore:0x0055d10f10d9a8>
	/usr/local/bundle/gems/fakes3-0.2.4/lib/fakes3/file_store.rb:231:in `block in combine_object_parts'
	/usr/local/bundle/gems/fakes3-0.2.4/lib/fakes3/file_store.rb:224:in `each'
	/usr/local/bundle/gems/fakes3-0.2.4/lib/fakes3/file_store.rb:224:in `combine_object_parts'
	/usr/local/bundle/gems/fakes3-0.2.4/lib/fakes3/server.rb:251:in `do_POST'
	/usr/local/lib/ruby/2.3.0/webrick/httpservlet/abstract.rb:107:in `service'
	/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

I am using docker and running 
with ruby:2.3.0-alpine

Thanks in advance
Regards
Ben

**Comment by aessig** [comment]
I have the same problem. Anyone ?

**Comment by ndench** [comment]
This appears to be a duplicate of #127
