### ISSUE TITLE
[Question] Does fake-s3 support copy file with Chinese file name?

### ISSUE THREAD

**Issue by calvin620707** [jubos/fake-s3#183]
I encountered a problem when tried to copy a file which file name (key) contain Chinese from one bucket to another bucket. I'm not sure if this is a bug or limitation/known issue of fake-s3? 

From the error logs of fake-s3, it looks like fake-s3 tried to access a file which file name be encoded by URL encode and file not found error happened.

I used python boto3 to copy file. The issue shouldn't related to boto3 since I can use boto3 to copy file which naming in English.

**Reproduce**
```
docker run --name my_s3 -p 4569:4569 -d lphoward/fake-s3
```

Use iPython to run following script
```
In [1]: import os, boto3

In [2]: s3 = boto3.resource('s3', endpoint_url='http://localhost:4569')

In [3]: bucket = s3.Bucket('test_bucket')

In [4]: bucket.upload_file('部落衝突.png', '部落衝突.png')

In [5]: other_bucket = s3.Bucket('other_bucket')

In [6]: copy_src = {'Bucket': 'test_bucket', 'Key': '部落衝突.png'}

In [7]: other_bucket.copy(copy_src, '部落衝突.png')
```

**Error output from fake-s3 docker**
```console
172.17.0.1 - - [05/Feb/2017:09:45:41 UTC] "PUT /other_bucket/%E9%83%A8%E8%90%BD%E8%A1%9D%E7%AA%81.png HTTP/1.1" 500 430
- -> /other_bucket/%E9%83%A8%E8%90%BD%E8%A1%9D%E7%AA%81.png
[2017-02-05 09:45:45] ERROR Errno::ENOENT: No such file or directory @ rb_sysopen - /fakes3_root/test_bucket/%E9%83%A8%E8%90%BD%E8%A1%9D%E7%AA%81.png/.fakes3_metadataFFF/metadata
	/var/lib/gems/2.1.0/gems/fakes3-0.2.5/lib/fakes3/file_store.rb:109:in `initialize'
	/var/lib/gems/2.1.0/gems/fakes3-0.2.5/lib/fakes3/file_store.rb:109:in `open'
	/var/lib/gems/2.1.0/gems/fakes3-0.2.5/lib/fakes3/file_store.rb:109:in `copy_object'
	/var/lib/gems/2.1.0/gems/fakes3-0.2.5/lib/fakes3/server.rb:177:in `do_PUT'
	/usr/lib/ruby/2.1.0/webrick/httpservlet/abstract.rb:106:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by pickhardt** [comment]
Apparently not. I just wrote a test for it and am seeing a similar problem:

```
<"中国的长城">(UTF-8) expected but was
<"\xE4\xB8\xAD\xE5\x9B\xBD\xE7\x9A\x84\xE9\x95\xBF\xE5\x9F\x8E">(ASCII-8BIT)

diff:
? 中国的长城     
? 中国的长城
  
? Encoding: UTF  -8   
?           ASCII  BIT
```
