### ISSUE TITLE
Can't delete multiple objects with aws-sdk-rails

### ISSUE THREAD

**Issue by bjoerne2** [jubos/fake-s3#212]
Hi!

I'd like to delete multiple objects and tried the newest master version with the latest commit DeleteObjects (#154) dcbe393b13651514aca44856c3cf3c823332d144 which supports deletion of multiple objects.

But unfortunately it doesn't work.

I'm accessing Fakes3 with the official library aws-sdk-rails. In my code it looks like this:

```
client.delete_objects({
  bucket: some_bucket
  delete: {
    objects: hash_with_keys
  }
})
```

This leads to a POST request with the URL **/?delete**. The data is in the request body.

In Fakes3 this causes an exception:

ERROR FakeS3::UnsupportedOperation: FakeS3::UnsupportedOperation
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fake-s3-dcbe393b1365/lib/fakes3/server.rb:369:in `normalize_delete'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fake-s3-dcbe393b1365/lib/fakes3/server.rb:499:in `normalize_request'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fake-s3-dcbe393b1365/lib/fakes3/server.rb:326:in `do_DELETE'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fake-s3-dcbe393b1365/lib/fakes3/server.rb:247:in `do_POST'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpservlet/abstract.rb:107:in `service'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/Users/bjoerne/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

Is this kind of deletion not supported?

**Comment by bjoerne2** [comment]
I opened a pull request: https://github.com/jubos/fake-s3/pull/213
