### ISSUE TITLE
undefined method `md5' for nil:NilClass

### ISSUE THREAD

**Issue by jarrett** [jubos/fake-s3#66]
When uploading any file, I get this exception:

```
 ERROR NoMethodError: undefined method `md5' for nil:NilClass
```

The exception is raised in [server.rb](https://github.com/jubos/fake-s3/blob/master/lib/fakes3/server.rb#L151):

```
response.header['ETag'] = "\"#{real_obj.md5}\""
```

So `real_obj` is nil. Further, the request times out. I don't know if the timeout causes `real_obj` to be nil or vice versa. Oddly, the file is successfully persisted and can be downloaded. This occurs for the master branch and the current version on rubygems.org (0.1.5.2).

The full shell session looks like this:

```
bundle exec fakes3 --root ~/fakes3 --port 10001

Loading FakeS3 with /Users/username/fakes3 on port 10001 with hostname s3.amazonaws.com
[2014-09-03 15:51:09] INFO  WEBrick 1.3.1
[2014-09-03 15:51:09] INFO  ruby 2.1.0 (2013-12-25) [x86_64-darwin12.0]
[2014-09-03 15:51:09] INFO  WEBrick::HTTPServer#start: pid=35502 port=10001
WEBrick::HTTPStatus::RequestTimeout
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httprequest.rb:525:in `rescue in _read_data'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httprequest.rb:518:in `_read_data'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httprequest.rb:534:in `read_data'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httprequest.rb:477:in `read_body'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httprequest.rb:255:in `body'
/Users/username/.rvm/gems/ruby-2.1.0/bundler/gems/fake-s3-67f5a3517970/lib/fakes3/file_store.rb:175:in `block in store_object'
/Users/username/.rvm/gems/ruby-2.1.0/bundler/gems/fake-s3-67f5a3517970/lib/fakes3/file_store.rb:174:in `open'
/Users/username/.rvm/gems/ruby-2.1.0/bundler/gems/fake-s3-67f5a3517970/lib/fakes3/file_store.rb:174:in `store_object'
/Users/username/.rvm/gems/ruby-2.1.0/bundler/gems/fake-s3-67f5a3517970/lib/fakes3/server.rb:150:in `do_PUT'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpservlet/abstract.rb:106:in `service'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2014-09-03 15:51:57] ERROR NoMethodError: undefined method `md5' for nil:NilClass
  /Users/username/.rvm/gems/ruby-2.1.0/bundler/gems/fake-s3-67f5a3517970/lib/fakes3/server.rb:151:in `do_PUT'
  /Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpservlet/abstract.rb:106:in `service'
  /Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/username/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
localhost - - [03/Sep/2014:15:51:27 EDT] "PUT /my_bucket/c80f5dcbaf70116a106cad087acc008e64e42d2f9cf4479e1ab77f4596cabe5ff5a8cb13ccd68f3fa85c5944c8eb63329206d010ef8fba3112f21bdd28167072 HTTP/1.1" 500 320
- -> /my_bucket/c80f5dcbaf70116a106cad087acc008e64e42d2f9cf4479e1ab77f4596cabe5ff5a8cb13ccd68f3fa85c5944c8eb63329206d010ef8fba3112f21bdd28167072
localhost - - [03/Sep/2014:15:51:58 EDT] "PUT /my_bucket/c80f5dcbaf70116a106cad087acc008e64e42d2f9cf4479e1ab77f4596cabe5ff5a8cb13ccd68f3fa85c5944c8eb63329206d010ef8fba3112f21bdd28167072 HTTP/1.1" 200 0
- -> /my_bucket/c80f5dcbaf70116a106cad087acc008e64e42d2f9cf4479e1ab77f4596cabe5ff5a8cb13ccd68f3fa85c5944c8eb63329206d010ef8fba3112f21bdd28167072
```

**Comment by phillipsnick** [comment]
I'm seem to be having the same/similar problem when attempting to upload files via the PHP SDK https://github.com/aws/aws-sdk-php

Log file, noting that the PHP app makes 4 attempts:

```
projectname.dev - - [12/Feb/2015:14:17:12 UTC] "HEAD /nicks-test1.txt HTTP/1.1" 404 0
- -> /nicks-test1.txt
/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/xml_adapter.rb:118: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/xml_adapter.rb:118: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/xml_adapter.rb:118: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/xml_adapter.rb:118: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
projectname.dev - - [12/Feb/2015:14:17:12 UTC] "HEAD / HTTP/1.1" 200 0
- -> /
[2015-02-12 14:17:12] ERROR NoMethodError: undefined method `md5' for nil:NilClass
	/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/server.rb:174:in `do_PUT'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpservlet/abstract.rb:106:in `service'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
projectname.dev - - [12/Feb/2015:14:17:12 UTC] "PUT /nicks-test1.txt HTTP/1.1" 500 356
- -> /nicks-test1.txt
[2015-02-12 14:17:13] ERROR NoMethodError: undefined method `md5' for nil:NilClass
	/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/server.rb:174:in `do_PUT'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpservlet/abstract.rb:106:in `service'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
projectname.dev - - [12/Feb/2015:14:17:13 UTC] "PUT /nicks-test1.txt HTTP/1.1" 500 356
- -> /nicks-test1.txt
[2015-02-12 14:17:15] ERROR NoMethodError: undefined method `md5' for nil:NilClass
	/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/server.rb:174:in `do_PUT'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpservlet/abstract.rb:106:in `service'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
projectname.dev - - [12/Feb/2015:14:17:15 UTC] "PUT /nicks-test1.txt HTTP/1.1" 500 356
- -> /nicks-test1.txt
[2015-02-12 14:17:19] ERROR NoMethodError: undefined method `md5' for nil:NilClass
	/usr/local/rvm/gems/ruby-2.2.0/gems/fakes3-0.1.7/lib/fakes3/server.rb:174:in `do_PUT'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpservlet/abstract.rb:106:in `service'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
projectname.dev - - [12/Feb/2015:14:17:19 UTC] "PUT /nicks-test1.txt HTTP/1.1" 500 356
- -> /nicks-test1.txt
```

PHP Error:

```Could not write the "nicks-test1.txt" key content.```

Bucket directory on file system

```
vagrant@s3:~/projectname$ ls -la
total 12
drwxrwxr-x 3 vagrant vagrant 4096 Feb 12 14:17 .
drwxr-xr-x 6 vagrant vagrant 4096 Feb 12 14:16 ..
drwxrwxr-x 3 vagrant vagrant 4096 Feb 12 14:17 nicks-test1.txt
```

```
vagrant@s3:~/projectname/nicks-test1.txt$ ls -la
total 12
drwxrwxr-x 3 vagrant vagrant 4096 Feb 12 14:17 .
drwxrwxr-x 3 vagrant vagrant 4096 Feb 12 14:17 ..
drwxrwxr-x 2 vagrant vagrant 4096 Feb 12 14:17 .fakes3_metadataFFF
```

```
vagrant@s3:~/projectname/nicks-test1.txt/.fakes3_metadataFFF$ ls -la
total 8
drwxrwxr-x 2 vagrant vagrant 4096 Feb 12 14:17 .
drwxrwxr-x 3 vagrant vagrant 4096 Feb 12 14:17 ..
```

**Comment by phillipsnick** [comment]
After 2-3 hours of messing around trying to get my head around this I finally worked it out!

When you put the object you need to define the content length. eg

```php
 $s3->putObject(array(
    'Bucket' => 'comic-relief',
    'Key' => 'nicks-test-php.txt',
    'ContentLength' => filesize($url),
    'Body'   => fopen($url, 'r'),
));
```

Hope that helps someone else out :)

**Comment by tyoshizawa** [comment]
I'm having similar issue with python boto 2.36.0 when createing bucketboto.
fake-s3: docker smaj/spurious-s3 image : 0.1.6.1,
              docker pandasuite/fakes3 image : 0.1.6.1
              docker my local build: 0.2.0

**Comment by schumannd** [comment]
Thank you tyoshizawa! I wasted a whole day on this issue. the iphoward/fake-s3 image just works.

**Comment by GregorioDiStefano** [comment]
This error also reproduces if the disk is out of space....

**Comment by BroiSatse** [comment]
Also happens to me. In my case it is that I have an encrypted home folder, that restricts file names to 143bytes and Paperclip gem can generate longer names, changing paperclip `path` option did the trick.

In short, this happens when saving the file to the disk failed. Nicer exception message would be nice though.
